import { useEffect, useState } from 'react';
import { TrendingUp, Award, Target, Activity } from 'lucide-react';

export default function Performance() {
  const [stats, setStats] = useState<any>(null);

  useEffect(() => {
    fetch('/api/performance')
      .then((res) => res.json())
      .then((data) => setStats(data))
      .catch((err) => console.error(err));
  }, []);

  if (!stats) return <div className="text-center py-20 text-gray-500">Loading performance data...</div>;

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-4xl font-bold text-white tracking-tight">Performance Dashboard</h1>
        <p className="text-gray-400 mt-2">Historical win rate and statistics from closed signals.</p>
      </div>

      <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="bg-white/5 border border-white/10 p-6 rounded-2xl">
          <div className="flex items-center gap-3 mb-2">
            <Award className="w-5 h-5 text-yellow-500" />
            <h3 className="text-gray-400 font-medium">Win Rate</h3>
          </div>
          <div className="text-4xl font-bold text-white">{stats.winRate}%</div>
          <div className="text-sm text-gray-500 mt-2">{stats.wins} W / {stats.losses} L</div>
        </div>

        <div className="bg-white/5 border border-white/10 p-6 rounded-2xl">
          <div className="flex items-center gap-3 mb-2">
            <TrendingUp className="w-5 h-5 text-green-500" />
            <h3 className="text-gray-400 font-medium">Total Pips</h3>
          </div>
          <div className="text-4xl font-bold text-green-400">+{stats.totalPips}</div>
          <div className="text-sm text-gray-500 mt-2">Across {stats.totalTrades} total trades</div>
        </div>

        <div className="bg-white/5 border border-white/10 p-6 rounded-2xl">
          <div className="flex items-center gap-3 mb-2">
            <Target className="w-5 h-5 text-blue-500" />
            <h3 className="text-gray-400 font-medium">Average R:R</h3>
          </div>
          <div className="text-4xl font-bold text-white">{stats.avgRR}</div>
          <div className="text-sm text-gray-500 mt-2">Risk to Reward Ratio</div>
        </div>

        <div className="bg-white/5 border border-white/10 p-6 rounded-2xl">
          <div className="flex items-center gap-3 mb-2">
            <Activity className="w-5 h-5 text-purple-500" />
            <h3 className="text-gray-400 font-medium">Entry Models</h3>
          </div>
          <div className="text-2xl font-bold text-white">{stats.sniperTrades} <span className="text-sm font-normal text-gray-500">Sniper</span></div>
          <div className="text-2xl font-bold text-white">{stats.smcTrades} <span className="text-sm font-normal text-gray-500">SMC</span></div>
        </div>
      </div>

      <div className="bg-black border border-white/10 rounded-2xl p-8 mt-8">
        <h2 className="text-2xl font-bold text-white mb-4">Disclaimer</h2>
        <p className="text-gray-400 leading-relaxed">
          The performance metrics shown above are based on historical signals generated by the SMC + Sniper engine. Past performance is not indicative of future results. Trading foreign exchange on margin carries a high level of risk and may not be suitable for all investors. The high degree of leverage can work against you as well as for you. Before deciding to trade foreign exchange, you should carefully consider your investment objectives, level of experience, and risk appetite.
        </p>
      </div>
    </div>
  );
}
